import { Navbar } from "@/components/Navbar";
import "./globals.css";
import SessionWrapper from "@/components/SessionWrapper";
import { Toaster } from "@/components/ui/sonner";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body className={`antialiased`}>
        <SessionWrapper>
          <Toaster />
          <Navbar/>
          {children}
        </SessionWrapper>
      </body>
    </html>
  );
}
